# Generated by Django 4.1.3 on 2023-01-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainposts',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='mainposts',
            name='image',
            field=models.CharField(db_index=True, default=12, max_length=200),
            preserve_default=False,
        ),
    ]
