# Generated by Django 4.1.3 on 2023-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_mainposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainposts',
            name='body',
            field=models.TextField(db_index=True, max_length=1500, verbose_name='Текст'),
        ),
    ]
