# Generated by Django 4.1.3 on 2023-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_emploee_order_size_status_orderstatus_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link_icons',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
