# Generated by Django 4.1.3 on 2023-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_link_icons_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link_icons',
            field=models.ImageField(upload_to='shop/icons_cat/%Y/%m/%d', verbose_name='Иконки'),
        ),
    ]
