# Generated by Django 4.1.3 on 2023-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_link_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='link_icons',
            field=models.ImageField(upload_to='shop/icons_cat/%Y/%m/%d', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
