# Generated by Django 4.1.3 on 2023-02-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=2, verbose_name='Каталожный номер'),
            preserve_default=False,
        ),
    ]
