# Generated by Django 4.1.7 on 2023-03-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='order',
            name='emploee',
        ),
        migrations.AddField(
            model_name='order',
            name='emploee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.emploee'),
        ),
    ]
