# Generated by Django 4.1.7 on 2023-03-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
