# Generated by Django 4.1.7 on 2023-03-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.IntegerField()),
                ('product', models.IntegerField()),
            ],
        ),
    ]
