# Generated by Django 4.1.7 on 2023-03-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_myorderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrderProduct',
        ),
    ]
