# Generated by Django 4.1.7 on 2023-03-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_delete_myorderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
