# Generated by Django 4.1.7 on 2023-03-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='name_status',
            new_name='status_id',
        ),
    ]
